#!/bin/sh 
#

mkdir /gpfs/hps3/stmp/Benjamin.Blake
mkdir /gpfs/hps3/stmp/Benjamin.Blake/work
cd /gpfs/hps3/stmp/Benjamin.Blake/work

. /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.v4.0.0/hrrr.ver
cp /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/sms/jhrrr_fcst_XX.bsub .
cycles="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
for cyc in $cycles; do
 cp jhrrr_fcst_XX.bsub jhrrr_fcst_${cyc}.bsub
 vi jhrrr_fcst_${cyc}.bsub << EOF 
   :1,\$ s/XX/${cyc}
   :wq
EOF
mv jhrrr_fcst_${cyc}.bsub /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/sms/.
done
exit
