#!/bin/sh 
#

mkdir /gpfs/hps3/stmp/Benjamin.Blake/work
cd /gpfs/hps3/stmp/Benjamin.Blake/work

. /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/versions/hrrr.ver
cp /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${model_ver}/sms/jhrrr_analysis_XX.bsub .
cycles="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
for cyc in $cycles; do
 cp jhrrr_analysis_XX.bsub jhrrr_analysis_${cyc}.bsub
 vi jhrrr_analysis_${cyc}.bsub << EOF 
   :1,\$ s/XX/${cyc}
   :wq
EOF
mv jhrrr_analysis_${cyc}.bsub /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${model_ver}/sms/.
done
exit
