#!/bin/ksh
#--------------------------------------------------------------------
# Example #1: convert a t574 file with 4 soil layers and noah lsm
# physics and NO landice, to a 574 file with 2 soil layers and
# osu lsm physics (and no landice).
#--------------------------------------------------------------------
export CLIMO_FIELDS_OPT=3
export LANDICE_OPT=3
export IVSSFC=200004
export LSOIL=2
export SIGINP=/gpfs/td1/global/noscrub/Shrinivas.Moorthi/data/siganl.gfs.2012102300
export SFCOUT=sfc.out
#export DATA=/gpfs/td1/meso/save/Eugene.Mirvis/SP_debug/WCOSS/utest/global_chgres_lst
export DATA=./
export MYTHREADS=16
./global_chgres.sh  /gpfs/td1/global/noscrub/Shrinivas.Moorthi/data/siganl.gfs.2012102300 \
                   ./t574.sfc.input.file \
                    out_one_574-574 \
                   ./t574.sfc.output.file  \
                    574 0 1760 880 
export MYTHREADS=12
./global_chgres.sh  /gpfs/td1/global/noscrub/Shrinivas.Moorthi/data/siganl.gfs.2012102300 \
                   ./t574.sfc.input.file \
                    out_one_574-574 \
                   ./t574.sfc.output.file  \
                      574 0 1760 880 
export MYTHREADS=10
./global_chgres.sh  /gpfs/td1/global/noscrub/Shrinivas.Moorthi/data/siganl.gfs.2012102300 \
                   ./t574.sfc.input.file \
                    out_one_574-574 \
                   ./t574.sfc.output.file  \
                      574 0 1760 880
export MYTHREADS=8
./global_chgres.sh  /gpfs/td1/global/noscrub/Shrinivas.Moorthi/data/siganl.gfs.2012102300 \
                   ./t574.sfc.input.file \
                    out_one_574-574 \
                   ./t574.sfc.output.file  \
                      574 0 1760 880 
export MYTHREADS=6
./global_chgres.sh  /gpfs/td1/global/noscrub/Shrinivas.Moorthi/data/siganl.gfs.2012102300 \
                   ./t574.sfc.input.file \
                    out_one_574-574 \
                   ./t574.sfc.output.file  \
                      574 0 1760 880
export MYTHREADS=4
./global_chgres.sh  /gpfs/td1/global/noscrub/Shrinivas.Moorthi/data/siganl.gfs.2012102300 \
                   ./t574.sfc.input.file \
                    out_one_574-574 \
                   ./t574.sfc.output.file  \
                      574 0 1760 880
export MYTHREADS=2
./global_chgres.sh  /gpfs/td1/global/noscrub/Shrinivas.Moorthi/data/siganl.gfs.2012102300 \
                   ./t574.sfc.input.file \
                    out_one_574-574 \
                   ./t574.sfc.output.file  \
                      574 0 1760 880 
export MYTHREADS=1
./global_chgres.sh  /gpfs/td1/global/noscrub/Shrinivas.Moorthi/data/siganl.gfs.2012102300 \
                   ./t574.sfc.input.file \
                    out_one_574-574 \
                   ./t574.sfc.output.file  \
                      574 0 1760 880
#			574 0 1152 576
#                      574 0 1760 880
#                       384 0 1760 880
#                         574 0 768 384
#                       574 0 1152 576
#                        574 0 880 880
#                        574 0 1800 880
# 			574 0 1152 576
#			574 0 768 384
#			574 0 1760 880

