#!/bin/sh 
#

cd /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.v4.1.0/sms/hrrrdas/makesms

. /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/versions/hrrr.ver
cp ../jhrrrdas_enkf_d01_XX.qsub .
#cp ../jhrrrdas_enkf_d02_XX.qsub .
cycles="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
for cyc in $cycles; do
 cp jhrrrdas_enkf_d01_XX.qsub jhrrrdas_enkf_d01_${cyc}.qsub
# cp jhrrrdas_enkf_d02_XX.qsub jhrrrdas_enkf_d02_${cyc}.qsub

 vi jhrrrdas_enkf_d01_${cyc}.qsub << EOF 
   :1,\$ s/XX/${cyc}
   :wq
EOF

# vi jhrrrdas_enkf_d02_${cyc}.qsub << EOF 
#   :1,\$ s/XX/${cyc}
#   :wq
#EOF

done
exit
