#!/bin/sh 
#

cd /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.v4.1.0/sms/hrrrdas/makesms

cp ../jhrrrdas_obsdiag_XX.qsub .
cycles="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
for cyc in $cycles; do
 cp jhrrrdas_obsdiag_XX.qsub jhrrrdas_obsdiag_${cyc}.qsub
 vi jhrrrdas_obsdiag_${cyc}.qsub << EOF 
   :1,\$ s/XX/${cyc}
   :wq
EOF
done
exit
