#!/bin/sh 
#

cycles="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
mkdir /lfs/h2/emc/ptmp/Benjamin.Blake/work
cd /lfs/h2/emc/ptmp/Benjamin.Blake/work
. /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/versions/hrrr.ver

cp /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/sms/post/post_subh/jhrrr_post_fXXYY_HH.qsub .
hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17"
minutes="00 15 30 45"
for cyc in $cycles; do
for fhr in $hours; do
 for fmin in $minutes;do
 echo $cyc
 echo $fhr$fmin
 cp jhrrr_post_fXXYY_HH.qsub jhrrr_post_f${fhr}${fmin}_${cyc}.qsub
 vi jhrrr_post_f${fhr}${fmin}_${cyc}.qsub << EOF 
   :1,\$ s/XX/${fhr}
   :1,\$ s/HH/${cyc}
   :1,\$ s/YY/${fmin}
   :wq
EOF
mv jhrrr_post_f${fhr}${fmin}_${cyc}.qsub /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/sms/post/post_subh/
done
done

cp jhrrr_post_fXXYY_HH.qsub jhrrr_post_f1800_${cyc}.qsub
vi jhrrr_post_f1800_${cyc}.qsub << EOF
   :1,\$ s/XX/18
   :1,\$ s/HH/${cyc}
   :1,\$ s/YY/00
   :wq
EOF
mv jhrrr_post_f1800_${cyc}.qsub /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/sms/post/post_subh/.
done
exit
