#!/bin/sh 
#

cycles="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
mkdir /gpfs/hps3/stmp/Benjamin.Blake/work
cd /gpfs/hps3/stmp/Benjamin.Blake/work
. /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.v4.0.0/hrrr.ver

cp /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/sms/post/post_subh/jhrrr_post_fXXYY_HH.bsub .
hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17"
minutes="00 15 30 45"
for cyc in $cycles; do
for fhr in $hours; do
 for fmin in $minutes;do
 echo $cyc
 echo $fhr$fmin
 cp jhrrr_post_fXXYY_HH.bsub jhrrr_post_f${fhr}${fmin}_${cyc}.bsub
 vi jhrrr_post_f${fhr}${fmin}_${cyc}.bsub << EOF 
   :1,\$ s/XX/${fhr}
   :1,\$ s/HH/${cyc}
   :1,\$ s/YY/${fmin}
   :wq
EOF
mv jhrrr_post_f${fhr}${fmin}_${cyc}.bsub /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/sms/post/post_subh/
done
done

cp jhrrr_post_fXXYY_HH.bsub jhrrr_post_f1800_${cyc}.bsub
vi jhrrr_post_f1800_${cyc}.bsub << EOF
   :1,\$ s/XX/18
   :1,\$ s/HH/${cyc}
   :1,\$ s/YY/00
   :wq
EOF
mv jhrrr_post_f1800_${cyc}.bsub /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/sms/post/post_subh/.
done
exit
