#! /bin/sh -v

# Define the fortran compiler and options

WRFDIR=/scratch4/BMC/comgsi/mhu/code/WRFV3.9/WRFV3
UNGRIBDIR=/scratch4/BMC/comgsi/mhu/code/WPSV3.8.1/ungrib/src

FC  =  mpif90 -free -f90=ifort
#FLAGS= -g -traceback -O3 -fp-model precise -assume byterecl -fpe0 -DLINUX
FLAGS= -g -traceback -O3

G2_INC4     = -I${UNGRIBDIR}/ngl/g2
G2_LIB4     = -L${UNGRIBDIR}/ngl/g2 -lg2_4
JASPER_LIB  = -L/usr/lib64 -ljasper
PNG_LIB     = -L/usr/lib64 -lpng
Z_LIB       = -L/usr/lib64 -lz

INCLD=  -I${NETCDF}/include -I../../../include ${G2_INC4}
LIBS =  \
        ${G2_LIB4} ${JASPER_LIB} ${PNG_LIB} ${Z_LIB} \
        -L${NETCDF}/lib -lnetcdf -lnetcdff \
        -L${WRFDIR}/external/io_netcdf -lwrfio_nf \
        -L${UNGRIBDIR}/ngl/w3 -lw3


OBJS = grib2_read_mod.o process_SST.o sst14k.o sstGlobal2RR.o netCDFsub_geo.o update_SST_netcdf_mass.o

all: process_SST

process_SST: ${OBJS}
	${FC} -o process_SST.exe ${FLAGS} ${OBJS} ${LIBS} 

.SUFFIXES : .F90 .f90 .f .o

.F90.o :
	${FC} ${FLAGS} ${INCLD} -c $<

.f90.o :
	${FC} ${FLAGS} ${INCLD} -c $<

clean:
	/bin/rm -f *.o *.mod *.exe
