#!/bin/sh 
#

mkdir /gpfs/hps3/stmp/Benjamin.Blake
mkdir /gpfs/hps3/stmp/Benjamin.Blake/work
cd /gpfs/hps3/stmp/Benjamin.Blake/work

. /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.v4.0.0/hrrr.ver
cp /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/sms/prep/jhrrr_prep_radar_XXXX.bsub .
cp /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/sms/prep/jhrrr_prep_radar_XX60.bsub .
cycles="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
minutes="16 30 46"
for cyc in $cycles; do
for fmin in $minutes;do
 cp jhrrr_prep_radar_XXXX.bsub jhrrr_prep_radar_${cyc}${fmin}.bsub 
 vi jhrrr_prep_radar_${cyc}${fmin}.bsub << EOF 
   :1,\$ s/HH/${cyc}
   :wq
EOF
 vi jhrrr_prep_radar_${cyc}${fmin}.bsub << EOF
   :1,\$ s/MM/${fmin}
   :wq
EOF
mv jhrrr_prep_radar_${cyc}${fmin}.bsub /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/sms/prep/.
done

cp jhrrr_prep_radar_XX60.bsub jhrrr_prep_radar_${cyc}60.bsub
vi jhrrr_prep_radar_${cyc}60.bsub << EOF
  :1,\$ s/HH/${cyc}
  :wq
EOF
vi jhrrr_prep_radar_${cyc}60.bsub << EOF
  :1,\$ s/MM/60
  :wq
EOF
mv jhrrr_prep_radar_${cyc}60.bsub /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/sms/prep/.
done
exit
