#!/bin/sh 
#

mkdir /lfs/h2/emc/ptmp/Benjamin.Blake/work
cd /lfs/h2/emc/ptmp/Benjamin.Blake/work
. /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/versions/hrrr.ver

cp /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/sms/prep/jhrrr_prep_smoke_XX.qsub .
cycles="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
for cyc in $cycles; do
 cp jhrrr_prep_smoke_XX.qsub jhrrr_prep_smoke_${cyc}.qsub
 vi jhrrr_prep_smoke_${cyc}.qsub << EOF 
   :1,\$ s/XX/${cyc}
   :wq
EOF
mv jhrrr_prep_smoke_${cyc}.qsub /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/sms/prep/.
done
exit
