#!/bin/sh 
#

mkdir /gpfs/hps3/stmp/Benjamin.Blake/work
cd /gpfs/hps3/stmp/Benjamin.Blake/work

. /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/versions/hrrr.ver

cp /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${model_ver}/sms/post/wrfbufr/jhrrr_wrfbufr_fHH_XX.bsub .
#cycles="00 06 12 18"
#hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35"
cycles="01 02 03 04 05 07 08 09 10 11 13 14 15 16 17 19 20 21 22 23"
hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17"
for cyc in $cycles; do
for fhr in $hours; do
 echo $fhr
 cp jhrrr_wrfbufr_fHH_XX.bsub jhrrr_wrfbufr_f${fhr}_${cyc}.bsub
 vi jhrrr_wrfbufr_f${fhr}_${cyc}.bsub << EOF 
   :1,\$ s/HH/${fhr}
   :1,\$ s/XX/${cyc}
   :wq
EOF
mv jhrrr_wrfbufr_f${fhr}_${cyc}.bsub /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${model_ver}/sms/post/wrfbufr/.
done
done

cp /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${model_ver}/sms/post/wrfbufr/jhrrr_wrfbufr_f18_XX.bsub .
for cyc in $cycles; do
 echo $cyc
 cp jhrrr_wrfbufr_f18_XX.bsub jhrrr_wrfbufr_f18_${cyc}.bsub
 vi jhrrr_wrfbufr_f18_${cyc}.bsub << EOF 
   :1,\$ s/XX/${cyc}
   :wq
EOF
mv jhrrr_wrfbufr_f18_${cyc}.bsub /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${model_ver}/sms/post/wrfbufr/.
done

exit
