#! /bin/sh
set -e

module purge
module load intel
module load szip
module load hdf5
module load netcdf

make \
  'FC=ifort' \
  'FFLAGS=-g -C -free -I$(NETCDF)/include -I. -convert big_endian' \
  'LDFLAGS=-convert big_endian' \
  'LIBS=-L$(NETCDF)/lib -lnetcdff -L$(NETCDF)/lib -L$(HDF5)/lib -L$(SZIP)/lib -lnetcdf -lnetcdf -lhdf5_hl -lhdf5 -lszip' \
  clean all
