#!/bin/sh 
#

cd /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.v4.0.0/sms/hrrrdas/makesms

. /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.v4.0.0/hrrr.ver
cp ../jhrrrdas_obsdiagmean_XX.bsub .
cycles="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
for cyc in $cycles; do
 cp jhrrrdas_obsdiagmean_XX.bsub jhrrrdas_obsdiagmean_${cyc}.bsub
 vi jhrrrdas_obsdiagmean_${cyc}.bsub << EOF 
   :1,\$ s/XX/${cyc}
   :wq
EOF
done
exit
