#! /bin/sh
set -e

module purge
module load envvar/1.0
module load PrgEnv-intel/8.1.0
module load craype
module load intel/19.1.3.304
module load cray-mpich/8.1.7
module load hdf5/1.10.6
module load netcdf/4.7.4
module load pnetcdf/1.12.2

make \
  'FC=ftn' \
  'FFLAGS=-g -C -free -I$(NETCDF)/include -I. -convert big_endian -traceback' \
  'LDFLAGS=-convert big_endian' \
  'LIBS=-L$(NETCDF)/lib -lnetcdff -lnetcdf' \
  clean all
