#!/bin/ksh
set -xa

########################################
# HRRR 3 km Analysis 
########################################

######################################################
# The following two variables could be defined in the
# loadleveler submission script (the ecf script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}
export SENDECF=${SENDECF:-YES}

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hrrr}
export RUN=${RUN:-hrrr}
export model=${model:-hrrr}

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to ${DATAROOT}
# SENDECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to ${COMROOT}/$NET/${envir}
# COM_OUT: Directory for output file, default to ${COMROOT}/$NET/${envir}
# gespath: Directory for the guess or restart files, default to ${GESROOT}/${envir}
#####################################################################################
if [ "$RUN_ENVIR" != nco ]      ### For Developers, "group_name" is passed from the ECF script
then
  group_name=${group_name:-meso}
  package_name=${package_name:-hrrr}
#  . /${group_name}/save/${LOGNAME}/${package_name}${NWROOT}/parm/${package_name}_para_config
  export userid=${userid:-$LOGNAME}
fi

export PS4='$SECONDS + '
date

####################################
# obtain unique process id (pid) and make temp directory
####################################
export DATA=${DATAROOT}/hrrr_${dom}_anl_${envir}_${cyc}
mkdir -p $DATA
cd $DATA

if [ "${dom}" = hrrrdas ]; then
   echo "run diag for member =$ensmem"
   ensmemid=`printf %4.4i $ensmem`

   if [ $ensmem -eq 00 ]; then
     rm -fr mean
     mkdir mean
     cd mean
   else
     rm -fr mem${ensmemid}
     mkdir mem${ensmemid}
     cd mem${ensmemid}
   fi
fi

export cycle=t${cyc}z
export tmmark=tm00
export cycm1=`expr $cyc - 1`
if [ "$cyc" = 00 ]; then
cycm1=23
else
cycm1=$(printf "%02d" $cycm1)
fi

export pgmout="OUTPUT.$$"

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy files to /com directory
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}

####################################
# Specify Execution Areas
####################################
export HOMEhrrr=${HOMEhrrr:-${NWROOT}/${NET}.${hrrr_ver}}
export EXEChrrr=${EXEChrrr:-${HOMEhrrr}/exec}
export FIXhrrr=${FIXhrrr:-${HOMEhrrr}/fix/${dom}}
export PARMhrrr=${PARMhrrr:-${HOMEhrrr}/parm/${dom}}
export USHhrrr=${USHhrrr:-${HOMEhrrr}/ush/${dom}}

export FIXcrtm=${FIXcrtm:-${NWROOThps}/lib/crtm/${crtm_ver_analysis}/fix}
###########################################
# Run setpdy and initialize PDY variables
###########################################
setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COM=${COM:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${dom}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${dom}}
export COMINgfs=${COMINgfs:-$(compath.py gfs/prod)}
export COMINsst=${COMINsst:-${COMROOTp3}/gfs/${gfs_ver}}
export PREPDIR=${PREPDIR:-${COMRAP}/rap/${rap_ver}}
#export COMRAP=${COMRAP:-${COMROOT}/rap/prod}
export COMRAP_E=${COMRAP_E:-${COMRAP}}
export PREPDIR2=${PREPDIR2:-${COMIN}}
export DCOM=${DCOM:-${DCOMROOT}}
export FVCOM=${FVCOM:-${DCOM}/${PDY}/wgrdbul/glerl}
export FVCOMm1=${FVCOMm1:-${DCOM}/${PDYm1}/wgrdbul/glerl}

export gespath=${gespath:-$GESROOT/${envir}}
export HRRRGES_ENKF=${HRRRGES_ENKF:-$gespath/${NET}/hrrrges_enkf/${dom}}
export HRRRGES_SFC=${HRRRGES_SFC:-$gespath/${NET}/hrrrges_sfc/${dom}}
export HRRRDASGES=${HRRRDASGES:-$gespath/${NET}/hrrrdasges}
export RAPGES_SATBIAS=${RAPGES_SATBIAS:-${GESROOT}/${envir}/rap/rapges_satbias}

mkdir -m 775 -p $COM $COMOUT 

env

########################################################
# Execute the script.
${HRRR_ANALSH:-$HOMEhrrr/scripts/${dom}/exhrrr_analysis.sh}
########################################################

cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATA
if [ ${KEEPDATA} = NO -a $dom = conus ] ; then 
  if [ "${dom}" = hrrrdas ]; then
    rm -rf $DATA/mem${ensmemid} ;
  else
    rm -rf $DATA ; 
  fi
fi
date

