#!/bin/ksh -l
set -xa

########################################
# HRRR Job to process EnKF data
########################################

######################################################
# The following two variables could be defined in the
# loadleveler submission script (the ecf script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hrrr}
export RUN=${RUN:-hrrr}
export model=${model:-hrrr}

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to ${DATAROOT}
# SENDECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to ${COMROOT}/$NET/${envir}
# COM_OUT: Directory for output file, default to ${COMROOT}/$NET/${envir}
# gespath: Directory for the guess or restart files, default to ${GESROOT}/${envir}
#####################################################################################
if [ "$RUN_ENVIR" != nco ]      ### For Developers, "group_name" is passed from the ECF script
then
  group_name=${group_name:-meso}
  package_name=${package_name:-hrrr}
#  . /${group_name}/save/${LOGNAME}/${package_name}${NWROOT}/parm/${package_name}_para_config
  export userid=${userid:-$LOGNAME}
fi

export PS4='$SECONDS + '
date

####################################
# obtain unique process id (pid) and make temp directory
####################################
#export DATA=${DATAROOT}/${jobid}
export DATA=${DATAROOT}/hrrr_${dom}_process_enkf_${envir}_${cyc}
mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z
export tmmark=tm00

export cychrrr=`expr $cyc + 9`

if [ "$cyc" = 18 ]; then
cychrrr=03
else
cychrrr=$(printf "%02d" $cychrrr)
fi

export pgmout="OUTPUT.$$"

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy files to /com directory
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}

####################################
# Specify Execution Areas
####################################
export HOMEhrrr=${HOMEhrrr:-${NWROOT}/${NET}.${hrrr_ver}}
export EXEChrrr=${EXEChrrr:-${HOMEhrrr}/exec}
export FIXhrrr=${FIXhrrr:-${HOMEhrrr}/fix/${dom}}
export PARMhrrr=${PARMhrrr:-${HOMEhrrr}/parm/${dom}}
export USHhrrr=${USHhrrr:-${HOMEhrrr}/ush/${dom}}

###########################################
# Run setpdy and initialize PDY variables
###########################################
setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${dom}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${dom}}
export gespath=${gespath:-${GESROOT}/${envir}}
export HRRRGES_ENKF=${HRRRGES_ENKF:-$gespath/${RUN}/hrrrges_enkf/${dom}}
export HRRRGES_SFC=${HRRRGES_SFC:-$gespath/${RUN}/hrrrges_sfc/${dom}}
export COMINgfs=${COMINgfs:-$(compath.py gfs/prod)}
export HRRRDASBC=${HRRRDASBC:-$gespath/${NET}/hrrrdasbc}
export HRRRDASENSP=${HRRRDASENSP:-$gespath/${NET}/hrrrdasensp}

mkdir -m 775 -p $COM $COMOUT $HRRRDASENSP

mkdir -m 775 -p $HRRRDASBC $COMOUT
env

########################################################
# Execute the script.
${HRRR_PREP_ENKF:-$HOMEhrrr/scripts/${dom}/exhrrrdas_prep_enkf.sh}
########################################################

cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATA
if [ ${KEEPDATA} = NO ] ; then rm -rf $DATA ; fi

date

