#!/bin/ksh
set -xa

########################################
# HRRR 3 km Analysis 
########################################

######################################################
# The following two variables could be defined in the
# loadleveler submission script (the ecf script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}
export SENDECF=${SENDECF:-YES}

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hrrr}
export RUN=${RUN:-hrrr}
export model=${model:-hrrr}

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to ${DATAROOT}
# SENDECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to ${COMROOT}/$NET/${envir}
# COM_OUT: Directory for output file, default to ${COMROOT}/$NET/${envir}
# gespath: Directory for the guess or restart files, default to ${GESROOT}/${envir}
#####################################################################################
if [ "$RUN_ENVIR" != nco ]      ### For Developers, "group_name" is passed from the ECF script
then
  group_name=${group_name:-meso}
  package_name=${package_name:-hrrr}
#  . /${group_name}/save/${LOGNAME}/${package_name}${NWROOT}/parm/${package_name}_para_config
  export userid=${userid:-$LOGNAME}
fi

export PS4='$SECONDS + '
date

####################################
# obtain unique process id (pid) and make temp directory
####################################
export DATA=${DATAROOT}/hrrr_${dom}_anl_${envir}_${cyc}
mkdir -p $DATA
cd $DATA

if [ "${dom}" = hrrrdas ]; then
   echo "run diag for member =$ensmem"
   ensmemid=`printf %4.4i $ensmem`

   if [ $ensmem -eq 00 ]; then
     rm -fr mean
     mkdir mean
     cd mean
   else
     rm -fr mem${ensmemid}
     mkdir mem${ensmemid}
     cd mem${ensmemid}
   fi
fi

export cycle=t${cyc}z
export tmmark=tm00
export cycm1=`expr $cyc - 1`
if [ "$cyc" = 00 ]; then
cycm1=23
else
cycm1=$(printf "%02d" $cycm1)
fi

export pgmout="OUTPUT.$$"

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy files to /com directory
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}

####################################
# Specify Execution Areas
####################################
export HOMEhrrr=${HOMEhrrr:-${NWROOT}/${NET}.${hrrr_ver}}
export EXEChrrr=${EXEChrrr:-${HOMEhrrr}/exec}
export FIXhrrr=${FIXhrrr:-${HOMEhrrr}/fix/${dom}}
export PARMhrrr=${PARMhrrr:-${HOMEhrrr}/parm/${dom}}
export USHhrrr=${USHhrrr:-${HOMEhrrr}/ush/${dom}}

export FIXcrtm=${FIXcrtm:-${HOMEhrrr}/fix/crtm_v${crtm_ver}_coefficients}

###########################################
# Run setpdy and initialize PDY variables
###########################################
setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################

# for testing with canned data
#export COMROOT=${COMROOT:-/lfs/h2/emc/ptmp/Benjamin.Blake/com}
#export COM=${COM:-${COMROOT}/${NET}/${hrrr_ver}/${RUN}.${PDY}}
#export COMIN=${COMIN:-${COMROOT}/${NET}/${hrrr_ver}/${RUN}.${PDY}/${dom}}
#export COMOUT=${COMOUT:-${COMROOT}/${NET}/${hrrr_ver}/${RUN}.${PDY}/${dom}}
#export GESROOT=${GESROOT:-${COMROOT}/${NET}/${hrrr_ver}/nwges}

# for WCOSS2 ops
export COM=${COM:-$(compath.py ${envir}/${NET}/${hrrr_ver}/${RUN}.${PDY})}
export COMIN=${COMIN:-$(compath.py ${envir}/${NET}/${hrrr_ver}/${RUN}.${PDY}/${dom})}
export COMOUT=${COMOUT:-$(compath.py ${envir}/${NET}/${hrrr_ver}/${RUN}.${PDY}/${dom})}
export GESROOT=${GESROOT:-$(compath.py ${envir}/${NET}/${hrrr_ver}/nwges)}

export COMINgfs=${COMINgfs:-$(compath.py $envir/gfs/$gfs_ver)}
export COMINsst=${COMINsst:-$(compath.py $envir/gfs/$gfs_ver)}
export PREPDIR=${PREPDIR:-$(compath.py $envir/rap/$rap_ver)}
export COMRAP=${COMRAP:-$(compath.py $envir/rap/$rap_ver)}
export COMRAP_E=${COMRAP_E:-$(compath.py $envir/rap/$rap_ver)}
export PREPDIR2=${PREPDIR2:-${COMIN}}
#export DCOMROOT=${DCOMROOT:-/lfs/h1/ops/$envir/dcom}
export FVCOM=${FVCOM:-${DCOMROOT}/${PDY}/wgrdbul/glerl}
export FVCOMm1=${FVCOMm1:-${DCOMROOT}/${PDYm1}/wgrdbul/glerl}

export HRRRGES_ENKF=${HRRRGES_ENKF:-$GESROOT/hrrrges_enkf/${dom}}
export HRRRGES_SFC=${HRRRGES_SFC:-$GESROOT/hrrrges_sfc/${dom}}
export HRRRDASGES=${HRRRDASGES:-$GESROOT/hrrrdasges}
export RAPGES_SATBIAS=${RAPGES_SATBIAS:-$(compath.py $envir/rap/$rap_ver/nwges/rapges_satbias)}

mkdir -m 775 -p $COM $COMOUT 

env

########################################################
# Execute the script.
${HRRR_ANALSH:-$HOMEhrrr/scripts/${dom}/exhrrr_analysis.sh}
########################################################

cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATA
if [ ${KEEPDATA} = NO -a $dom = conus ] ; then 
  if [ "${dom}" = hrrrdas ]; then
    rm -rf $DATA/mem${ensmemid} ;
  else
    rm -rf $DATA ; 
  fi
fi
date

