#!/bin/ksh -l
set -xa
export MP_IOAGENT_CNT=all
export MP_IO_BUFFER_SIZE=8M

########################################
# HRRR Sub-Hourly Post Processing
########################################

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the sms script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hrrr}
export RUN=${RUN:-hrrr}
export model=${model:-hrrr}

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to ${DATAROOT}
# SENDSMS: If the job is to be running using SMS, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to ${COMROOT}/$NET/${envir}
# COM_OUT: Directory for output file, default to ${COMROOT}/$NET/${envir}
# gespath: Directory for the guess or restart files, default to ${GESROOT}/${envir}
#####################################################################################
if [ "$RUN_ENVIR" != nco ]      ### For Developers, "group_name" is passed from the SMS script
then
  group_name=${group_name:-meso}
  package_name=${package_name:-hrrr}
#  . /${group_name}/save/${LOGNAME}/${package_name}${NWROOT}/parm/${package_name}_para_config
  export userid=${userid:-$LOGNAME}
fi


export PS4='$SECONDS + '
date

####################################
# obtain unique process id (pid) and make temp directory
####################################
export DATA=${DATAROOT}/hrrr_${dom}_post_${envir}_${cyc}_f${fhr}${fmin}
export POSTMGRDIR=${DATAROOT}/hrrr_${dom}_postmgr_subh_${envir}_${cyc}
mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z
export fhrm1=`expr $fhr - 1`
fhrm1=$(printf "%02d" $fhrm1)

export pgmout="OUTPUT.$$"

####################################
# SENDSMS  - Flag Events on SMS
# SENDCOM  - Copy files to /com directory
####################################
export SENDSMS=${SENDSMS:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}

## Turn off Alaska wmo alerts for now
if [ $dom = alaska ]; then
  export SENDDBN_NTC=NO
fi
export ALERT_EXT=${ALERT_EXT:-}

####################################
# Specify Execution Areas
####################################
export HOMEhrrr=${HOMEhrrr:-${NWROOT}/${NET}.${hrrr_ver}}
export EXEChrrr=${EXEChrrr:-${HOMEhrrr}/exec}
export FIXhrrr=${FIXhrrr:-${HOMEhrrr}/fix/${dom}}
export PARMhrrr=${PARMhrrr:-${HOMEhrrr}/parm/${dom}}
export USHhrrr=${USHhrrr:-${HOMEhrrr}/ush/${dom}}
export GEMPAKhrrr=${GEMPAKhrrr:-$HOMEhrrr/gempak}

export FIXcrtm_post=${FIXcrtm_post:-${NWROOThps}/lib/crtm/${crtm_ver_post}/src/fix}

###########################################
# Run setpdy and initialize PDY variables
###########################################
setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${dom}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${dom}}
export COMNAWP=${COMNAWP:-${COMOUT}/gempak}
export WMO=${WMO:-${COMOUT}/wmo}

env
export INPUT_DATA=${DATAROOT}/hrrr_${dom}_fcst_${envir}_${cyc}

mkdir -m 775 -p $COMOUT $PCOM $COMNAWP

env

########################################################
# Execute the script.
${HRRR_POSTSH:-$HOMEhrrr/scripts/${dom}/exhrrr_postsubh.sh}
########################################################

cat $pgmout

msg="ENDED NORMALLY."
#postmsg "$jlogfile" "$msg"

export KEEPDATA=YES
##############################
# Remove the Temporary working directory
##############################
cd $DATA
if [ ${KEEPDATA} = NO ] ; then rm -rf $DATA ; fi

date

