#!/bin/bash
#PBS -j oe
#PBS -o /lfs/h2/emc/ptmp/Benjamin.Blake/outputhrrrak/hrrr_makeguess.out18z
#PBS -e /lfs/h2/emc/ptmp/Benjamin.Blake/outputhrrrak/hrrr_makeguess.out18z
#PBS -N hrrr_makeguess_18
#PBS -l walltime=00:15:00
#PBS -q "dev"
#PBS -A HRRR-DEV
#PBS -l select=1:ncpus=128

set -x

# Set MPI options
export OMP_NUM_THREADS=1
export MP_TASK_AFFINITY=core:1
export KMP_AFFINITY=disabled
export MP_MPILIB=mpich2

export envir=prod
export RUN_ENVIR=prod
export cyc=18
export job=hrrr_makeguess_18
export group_name=meso

. /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/versions/hrrr.ver
. /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/driver/hrrrakwcoss2.env

module use ${NWROOT}/hrrr.${hrrr_ver}/modulefiles
module load HRRR/v4.0.0

# CALL executable job script here
${NWROOT}/hrrr.${hrrr_ver}/jobs/JHRRR_MAKEGUESS
qsub /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/prep/jhrrr_prep_radar_1816.qsub
qsub /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/prep/jhrrr_prep_radar_1830.qsub
qsub /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/prep/jhrrr_prep_radar_1846.qsub
sleep 60
qsub /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/prep/jhrrr_prep_radar_1860.qsub
qsub /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/prep/jhrrr_prep_cloud_18.qsub
qsub /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/prep/jhrrr_prep_smoke_18.qsub
