#!/bin/sh 
#

mkdir /lfs/h2/emc/ptmp/Benjamin.Blake/work
cd /lfs/h2/emc/ptmp/Benjamin.Blake/work

cp /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.v4.1.0/smsak/jhrrr_gempak_XX.qsub .
cycles="00 03 06 09 12 15 18 21"
for cyc in $cycles; do
 cp jhrrr_gempak_XX.qsub jhrrr_gempak_${cyc}.qsub
 vi jhrrr_gempak_${cyc}.qsub << EOF 
   :1,\$ s/XX/${cyc}
   :wq
EOF
mv jhrrr_gempak_${cyc}.qsub /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.v4.1.0/smsak/.
done
exit
