#!/bin/sh 
#

mkdir /lfs/h2/emc/ptmp/Benjamin.Blake
mkdir /lfs/h2/emc/ptmp/Benjamin.Blake/work
cd /lfs/h2/emc/ptmp/Benjamin.Blake/work

. /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/versions/hrrr.ver
cp /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/jhrrr_fcst_XX.qsub .
cycles="00 03 06 09 12 15 18 21"
for cyc in $cycles; do
 cp jhrrr_fcst_XX.qsub jhrrr_fcst_${cyc}.qsub
 vi jhrrr_fcst_${cyc}.qsub << EOF 
   :1,\$ s/XX/${cyc}
   :wq
EOF
mv jhrrr_fcst_${cyc}.qsub /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/.
done
exit
