#!/bin/sh

###############################################
# Processes HRRR grib2 files into gempak files 
###############################################

set -xa

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the sms script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}

# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date
# 
# obtain unique process id (pid) and make temp directories
#
export DATA=${DATAROOT}/${jobid}
mkdir $DATA
cd $DATA 

export pgmout="OUTPUT.$$"

export cycle=t${cyc}z 

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

#
# Set up model and cycle specific variables
#
export NET=hrrr
export RUN=hrrr
export finc=1
export fstart=00
export model=hrrr

if [ $cyc -eq 00 -o $cyc -eq 06 -o $cyc -eq 12 -o $cyc -eq 18 ]; then
  export fend=36
else
  export fend=18
fi

#
# Now set up GEMPAK/NTRANS environment
#
. ${NWROOTp1}/gempak/.gempak

# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${dom}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${dom}/nawips}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi

env

export HOMEhrrr=${HOMEhrrr:-${NWROOT}/${NET}.${hrrr_ver}}
export SCRIPTShrrr=${SCRIPTShrrr:-$HOMEhrrr/scripts/${dom}}
export GEMPAKhrrr=${GEMPAKhrrr:-$HOMEhrrr/gempak}

export RUN=hrrr
export GRIB=wrfsfc
export DBN_ALERT_TYPE=HRRR_GEMPAK
export EXT=""
export ALERT_EXT=${ALERT_EXT:-}

########################################################
# Execute the script.
${HRRR_GEMPAKSH:-$SCRIPTShrrr/exhrrr_nawips.sh.ecf $RUN $GRIB $DBN_ALERT_TYPE $EXT}
########################################################
cd $DATA
if [ ${KEEPDATA} = NO ] ; then rm -rf $DATA ; fi

date
