# makefile for nssl_porcess
#! /bin/sh -v

# Define the fortran compiler and options

include configure.process

INCLD=  -I${NETCDF}/include -I../../../include -I/scratch2/portfolios/NCEPDEV/rstprod/nwprod/lib/incmod/g2_4
LIBS =  \
        -L/contrib/nceplibs/nwprod/lib -lg2tmpl \
        -L/contrib/nceplibs/nwprod/lib -lg2_4 \
        /home/Ratko.Vasic/lib_tmp/jasper.intel/lib/libjasper.a  \
        /home/Ratko.Vasic/lib_tmp/libpng.intel/lib/libpng.a \
        /scratch1/portfolios/NCEPDEV/nems/save/Jun.Wang/nwprod/libintel/sorc/zlib-1.2.5/libz.a \
        -L${NETCDF}/lib -lnetcdf -L${GSILIBS}

OBJS = netCDFsub.o netCDFsub_geo.o write_bufr_ref.o process_NSSL_mosaic.o \
       read_nssl_binary.o read_grib2_mod.o read_ncep_binary.o # read_grib2.o

# all: process_NSSL_mosaic read_grib2
all: process_NSSL_mosaic

process_NSSL_mosaic: ${OBJS}
	${FC} -o process_NSSL_mosaic.exe ${FLAGS} ${OBJS} ${LIBS} 

read_bufr: readbufr.o
	${FC} -o read_bufr.exe ${FLAGS} readbufr.o ${LIBS} 

read_grib2: read_grib2.o
	${FC} -o read_grib2.exe ${FLAGS} read_grib2.o ${LIBS} 

write_bufr: write_bufr_ref.o write_bufr_test.o
	${FC} -o write_bufr.exe ${FLAGS} write_bufr_ref.o write_bufr_test.o  ${LIBS} 

.SUFFIXES : .F90 .f90 .f .c .o

.F90.o :
	${FC} ${FLAGS} ${INCLD} -c $<

.f90.o :
	${FC} ${FLAGS} ${INCLD} -c $<

clean:
	/bin/rm -f *.o *.exe
