#!/bin/ksh --login

set -x
#source /u/Benjamin.Blake/.profile
. /opt/modules/default/init/ksh
module load xt-lsfhpc/9.1.3

####### Set up some paths needed by the j-job scripts #######
export NWROOTprod=/gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod
export COMROOTprod=/gpfs/dell1/nco/ops/com
export COMROOTp3=/gpfs/dell1/nco/ops/com
export DCOMROOT=/gpfs/dell1/nco/ops/dcom
export DATAROOT=/gpfs/hps/ptmp/Benjamin.Blake
export NWROOT=/gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod
export COMROOT=${DATAROOT}/com
export GESROOT=${DATAROOT}/nwges

export dom=hrrrdas
cyc=$1

cd /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.v4.0.0/sms/hrrrdas
bsub < jhrrrdas_makebc_${cyc}.bsub
exit

