#!/bin/ksh --login

set -x
#source /u/Benjamin.Blake/.profile
. /opt/modules/default/init/ksh
module load xt-lsfhpc/9.1.3

. /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.v4.0.0/hrrr.ver

####### Set up some paths needed by the j-job scripts #######
export NWROOTprod=/gpfs/hps/nco/ops/nwprod
export COMROOTprod=/gpfs/hps/nco/ops/com
export COMROOTp1=/gpfs/gp1/nco/ops/com
export COMROOTp2=/gpfs/gp2/nco/ops/com
export DCOMROOTp1=/gpfs/gp1/nco/ops/dcom
export DATAROOT=/gpfs/hps3/ptmp/Benjamin.Blake
export DATAROOT2=/gpfs/hps3/ptmp/Ming.Hu
export NWROOT=/gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod
export COMROOT=${DATAROOT}/com
export COMROOT2=${DATAROOT2}/com
export GESROOT=${DATAROOT}/nwges

export dom=hrrrdas
export NUM_ENSGRP=12
export no_member=36

cyc=$1
ymd=`cut -c 7-14 /gpfs/hps/nco/ops/com/date/t${cyc}z`
#ymd=20191621
COMOUT=/gpfs/hps3/ptmp/Benjamin.Blake/com/hrrr/prod/hrrr.${ymd}/${dom}
SMSDIR=/gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/sms

ymdhm1="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -1 -1`"
echo $ymdhm1
cycm1=`echo $ymdhm1 | cut -c9-10`
ymdhm2="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -2 -1`"
echo $ymdhm2
cycm2=`echo $ymdhm2 | cut -c9-10`
ymdhm3="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -3 -1`"
echo $ymdhm3
cycm3=`echo $ymdhm3 | cut -c9-10`
ymdhm4="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -4 -1`"
echo $ymdhm4
cycm4=`echo $ymdhm4 | cut -c9-10`
typeset -Z2 cycm1 cycm2 cycm3 cycm4

ymdm2="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -48 -1`"
ymdm24="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -23 -1`"
rmm2=`echo $ymdm2 | cut -c1-8`
rmm24=`echo $ymdm24 | cut -c1-8`
echo $rmm2
if [ $cyc -eq 09 ]; then
  rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/com/hrrr/prod/hrrr.${rmm2}
fi
if [ $cyc -eq 09 ]; then
  rm -f /gpfs/hps3/ptmp/Benjamin.Blake/nwges/prod/hrrr/hrrrdasbc/wrfbdy_d??.${rmm24}*
  rm -f /gpfs/hps3/ptmp/Benjamin.Blake/nwges/prod/hrrr/hrrrdasbc/wrfinput_d??.${rmm24}*
  rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/nwges/prod/hrrr/hrrrdasensp/enspert_d??_${rmm24}*
  rm -f /gpfs/hps3/ptmp/Benjamin.Blake/nwges/prod/hrrr/hrrrdasges/hrrrdas_d??_${rmm24}*
  rm -f /gpfs/hps3/ptmp/Benjamin.Blake/nwges/prod/hrrr/hrrrdasges/hrrrdas_small_d02_${rmm24}*
fi

# Cleanup hrrrdasges files from cycm4
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/nwges/prod/hrrr/hrrrdasges/hrrrdas_d??_${ymdhm4}${cycm4}*


# Scrub cycm3 directories for all cycles
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_makebc_prod_${cycm3}
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_makeguess_${cycm3}
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_prep_cloud_${cycm3}
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_prep_radar_${cycm3}
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_anl_${cycm3}
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_fcst_${cycm3}
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_process_enkf_${cycm3}

#  submit 
bsub < ${SMSDIR}/hrrrdas/jhrrr_prep_radar_${cyc}.bsub
bsub < ${SMSDIR}/hrrrdas/jhrrr_prep_cloud_${cyc}.bsub
exit
