#!/bin/ksh --login

set -x
#source /u/Benjamin.Blake/.profile
. /opt/modules/default/init/ksh
module load xt-lsfhpc/9.1.3

. /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.v4.0.0/hrrr.ver

####### Set up some paths needed by the j-job scripts #######
export NWROOTprod=/gpfs/hps/nco/ops/nwprod
export COMROOTprod=/gpfs/hps/nco/ops/com
export COMROOTp3=/gpfs/dell1/nco/ops/com
export DCOMROOT=/gpfs/dell1/nco/ops/dcom
export DATAROOT=/gpfs/hps/ptmp/Benjamin.Blake
export DATAROOT2=/gpfs/hps3/ptmp/Ming.Hu
export NWROOT=/gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod
export COMROOT=${DATAROOT}/com
export COMROOT2=${DATAROOT2}/com
export GESROOT=${DATAROOT}/nwges

export dom=hrrrdas
export NUM_ENSGRP=18
export no_member=36
cyc=$1
ymd=`cut -c 7-14 /gpfs/hps/nco/ops/com/date/t${cyc}z`
#ymd=20191016
COMOUT=/gpfs/hps/ptmp/Benjamin.Blake/com/hrrr/prod/hrrr.${ymd}/${dom}
SMSDIR=/gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/sms

#bsub < ${SMSDIR}/hrrrdas/jhrrrdas_enkf_d01_${cyc}.bsub
bsub < ${SMSDIR}/hrrrdas/jhrrrdas_enkf_d02_${cyc}_test.bsub
#bsub < ${SMSDIR}/hrrrdas/jhrrrdas_makeguess_${cyc}.bsub
#bsub < ${SMSDIR}/hrrrdas/jhrrrdas_fcst_${cyc}_test.bsub
#bsub < ${SMSDIR}/hrrrdas/jhrrrdas_diagmgr_${cyc}.bsub
#bsub < ${SMSDIR}/hrrrdas/jhrrr_prep_radar_${cyc}.bsub
#export ENSGRP=3
#bsub < ${SMSDIR}/hrrrdas/jhrrrdas_obsdiagmean_${cyc}.bsub
exit
