#!/bin/ksh --login

set -x
#source /u/Benjamin.Blake/.profile
. /opt/modules/default/init/ksh
module load xt-lsfhpc/9.1.3

. /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.v4.0.0/hrrr.ver

####### Set up some paths needed by the j-job scripts #######
export NWROOTprod=/gpfs/hps/nco/ops/nwprod
export COMROOTprod=/gpfs/hps/nco/ops/com
export COMROOTp3=/gpfs/dell1/nco/ops/com
export DCOMROOT=/gpfs/dell1/nco/ops/dcom
export DATAROOT=/gpfs/hps3/ptmp/Benjamin.Blake
export DATAROOT2=/gpfs/hps3/ptmp/Benjamin.Blake
export NWROOT=/gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod
export COMROOT=${DATAROOT}/com
export COMROOT2=${DATAROOT2}/com
export GESROOT=${DATAROOT}/nwges
export GESROOT2=${DATAROOT2}/nwges

export dom=alaska
cyc=$1
ymd=`cut -c 7-14 /gpfs/hps/nco/ops/com/date/t${cyc}z`
COMOUT=/gpfs/hps3/ptmp/Benjamin.Blake/com/hrrr/prod/hrrr.${ymd}/${dom}
SMSDIR=/gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak

ymdhm1="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -1 -1`"
echo $ymdhm1
cycm1=`echo $ymdhm1 | cut -c9-10`
ymdhm2="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -2 -1`"
echo $ymdhm2
cycm2=`echo $ymdhm2 | cut -c9-10`
ymdhm3="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -3 -1`"
echo $ymdhm3
cycm3=`echo $ymdhm3 | cut -c9-10`
ymdhm4="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -4 -1`"
echo $ymdhm4
cycm4=`echo $ymdhm4 | cut -c9-10`
typeset -Z2 cycm1 cycm2 cycm3 cycm4

ymdm2="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -48 -1`"
ymdm24="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -23 -1`"
rmm2=`echo $ymdm2 | cut -c1-8`
rmm24=`echo $ymdm24 | cut -c1-8`
echo $rmm2

# submit job for current hour
#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/jhrrr_makebc_08.bsub
#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/jhrrr_makebc_09.bsub
#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/jhrrr_makebc_23.bsub
#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/jhrrr_makeguess_09.bsub
#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/jhrrr_fcstpre_09.bsub
#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/jhrrr_analysis_15.bsub
#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/prep/jhrrr_prep_smoke_08.bsub
#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/jhrrr_fcst_15.bsub
#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/post/wrfbufr/jhrrr_wrfbufr_f36_06.bsub
#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/jhrrr_sndp_15.bsub
#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/post/post/jhrrr_post_f01_09.bsub
#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/post/post/jhrrr_post_f02_09.bsub
#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/post/post/jhrrr_post_f03_09.bsub
#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/post/post_subh/jhrrr_post_f1415_10.bsub
#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/post/post_subh/jhrrr_post_f1430_10.bsub
#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/post/post_subh/jhrrr_post_f1445_10.bsub
#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/post/post_subh/jhrrr_post_f1500_10.bsub

#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/jhrrr_gempak_08.bsub
#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/jhrrr_sndp_09.bsub


#bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/post/jhrrr_postmgr_09.bsub
bsub < /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/post/jhrrr_postmgr_subh_09.bsub


exit
