#!/bin/ksh --login

set -x
#source /u/Benjamin.Blake/.profile
. /opt/modules/default/init/ksh
module load xt-lsfhpc/9.1.3

. /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.v4.0.0/hrrr.ver

####### Set up some paths needed by the j-job scripts #######
export NWROOTprod=/gpfs/hps/nco/ops/nwprod
export COMROOTprod=/gpfs/hps/nco/ops/com
export COMROOTp3=/gpfs/dell1/nco/ops/com
export DCOMROOT=/gpfs/dell1/nco/ops/dcom
export DATAROOT=/gpfs/hps/ptmp/Benjamin.Blake
export DATAROOT2=/gpfs/hps3/ptmp/Ming.Hu
export NWROOT=/gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod
export COMROOT=${DATAROOT}/com
export COMROOT2=${DATAROOT2}/com
export GESROOT=${DATAROOT}/nwges

export dom=conus
cyc=$1
ymd=`cut -c 7-14 /gpfs/hps/nco/ops/com/date/t${cyc}z`
COMOUT=/gpfs/hps/ptmp/Benjamin.Blake/com/hrrr/prod/hrrr.${ymd}/${dom}
SMSDIR=/gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/sms

ymdhm1="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -1 -1`"
echo $ymdhm1
cycm1=`echo $ymdhm1 | cut -c9-10`
ymdhm2="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -2 -1`"
echo $ymdhm2
cycm2=`echo $ymdhm2 | cut -c9-10`
ymdhm3="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -3 -1`"
echo $ymdhm3
cycm3=`echo $ymdhm3 | cut -c9-10`
ymdhm4="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -4 -1`"
echo $ymdhm4
cycm4=`echo $ymdhm4 | cut -c9-10`
typeset -Z2 cycm1 cycm2 cycm3 cycm4

ymdm2="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -48 -1`"
ymdm24="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -23 -1`"
rmm2=`echo $ymdm2 | cut -c1-8`
rmm24=`echo $ymdm24 | cut -c1-8`
echo $rmm2
if [ $cyc -eq 00 ]; then
  rm -rf /gpfs/hps/ptmp/Benjamin.Blake/com/hrrr/prod/hrrr.${rmm2}
fi
if [ $cyc -eq 03 ]; then
  rm -rf /gpfs/hps/ptmp/Benjamin.Blake/nwges/prod/hrrr/hrrrges_sfc/${dom}/hrrr_${rmm24}*
fi

rm -f /gpfs/hps/ptmp/Benjamin.Blake/outputhrrrconus/*${cyc}z

# submit boundary job for current hour
bsub < ${SMSDIR}/jhrrr_makebc_${cyc}.bsub
cd 

# Scrub cycm3 directories for all cycles
rm -rf /gpfs/hps/ptmp/Benjamin.Blake/hrrr_${dom}_makebc_prod_${cycm3}
rm -rf /gpfs/hps/ptmp/Benjamin.Blake/hrrr_${dom}_makeguess_prod_${cycm3}
rm -rf /gpfs/hps/ptmp/Benjamin.Blake/hrrr_${dom}_prep_cloud_prod_${cycm3}
rm -rf /gpfs/hps/ptmp/Benjamin.Blake/hrrr_${dom}_prep_radar_prod_${cycm3}
rm -rf /gpfs/hps/ptmp/Benjamin.Blake/hrrr_${dom}_prep_smoke_prod_${cycm3}
rm -rf /gpfs/hps/ptmp/Benjamin.Blake/hrrr_${dom}_ref2tten_prod_${cycm3}
rm -rf /gpfs/hps/ptmp/Benjamin.Blake/hrrr_${dom}_anl_prod_${cycm3}
rm -rf /gpfs/hps/ptmp/Benjamin.Blake/hrrr_${dom}_post_prod_${cycm3}*
rm -rf /gpfs/hps/ptmp/Benjamin.Blake/hrrr_${dom}_postmgr_prod_${cycm3}*
rm -rf /gpfs/hps/ptmp/Benjamin.Blake/hrrr_${dom}_postmgr_subh_prod_${cycm3}*
rm -rf /gpfs/hps/ptmp/Benjamin.Blake/hrrr_${dom}_wrfbufr_prod_${cycm3}*
rm -rf /gpfs/hps/ptmp/Benjamin.Blake/hrrr_${dom}_sndp_prod_${cycm3}
rm -rf /gpfs/hps/ptmp/Benjamin.Blake/hrrr_${dom}_fcst_pre_prod_${cycm3}
rm -rf /gpfs/hps/ptmp/Benjamin.Blake/hrrr_${dom}_fcst_prod_${cycm3}
rm -rf /gpfs/hps/ptmp/Benjamin.Blake/hrrr_${dom}_gempak_prod_${cycm3}
##rm /gpfs/hps3/ptmp/Benjamin.Blake/outputhrrr/hrrr*out${cycm4}z aiyaiya

if [ $cyc -eq 00 -o $cyc -eq 06 -o $cyc -eq 12 -o $cyc -eq 18 ]; then
# Wait 30 minutes before submitting makeguess
  sleep 1800
else
# Wait 5 minutes before submitting makeguess
  sleep 300
fi

#  submit makeguess
bsub < ${SMSDIR}/jhrrr_makeguess_${cyc}.bsub

exit
