#!/bin/ksh

set -x
#source /u/Benjamin.Blake/.profile
. /opt/modules/default/init/ksh
module load xt-lsfhpc/9.1.3

. /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.v4.0.0/hrrr.ver

####### Set up some paths needed by the J-job scripts #######
export NWROOTprod=/gpfs/hps/nco/ops/nwprod
export COMROOTprod=/gpfs/hps/nco/ops/com
export COMROOTp3=/gpfs/dell1/nco/ops/com
export DCOMROOT=/gpfs/dell1/nco/ops/dcom
export DATAROOT=/gpfs/hps3/ptmp/Benjamin.Blake
export DATAROOT2=/gpfs/hps3/ptmp/Ming.Hu
export NWROOT=/gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod
export COMROOT=${DATAROOT}/com
export COMROOT2=${DATAROOT2}/com
export GESROOT=${DATAROOT}/nwges
export GESROOT2=${DATAROOT2}/nwges

# opertional GDAS feed with this version:
#export FIXcrtm=/gpfs/hps/nco/ops/nwprod/lib/crtm/v2.2.3/fix

export dom=alaska
cyc=$1
ymd=`cut -c 7-14 /gpfs/hps/nco/ops/com/date/t${cyc}z`
COMOUT=/gpfs/hps3/ptmp/Benjamin.Blake/com/hrrr/prod/hrrr.${ymd}/${dom}
SMSDIR=/gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak

ymdhm1="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -1 -1`"
echo $ymdhm1
cycm1=`echo $ymdhm1 | cut -c9-10`
ymdhm2="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -2 -1`"
echo $ymdhm2
cycm2=`echo $ymdhm2 | cut -c9-10`
typeset -Z2 cycm1 cycm2

# submit boundary job from previous hour, needed for forecastpre
#sleep 2400
bsub < ${SMSDIR}/jhrrr_makebc_${cycm1}.bsub
bsub < ${SMSDIR}/jhrrr_makebc_${cyc}.bsub
cd 

rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_makeguess_${cyc}
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_anl_${cyc}
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_fcst_pre_${cyc}/*
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_fcst_${cyc}/*
sleep 1800
#  submit makeguess
bsub < ${SMSDIR}/jhrrr_makeguess_${cyc}.bsub

ymdm2="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -48 -1`"
rmm2=`echo $ymdm2 | cut -c1-8`
echo $rmm2
if [ $cyc -eq 06 ]; then
  rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/com/hrrr/prod/hrrr.${rmm2}
  rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/nwges/prod/hrrr/hrrrges_sfc/alaska/*${rmm2}* 
fi

# Scrub cycm9 directories for all cycles

ymdhm9="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -9 -1`"
echo $ymdhm9
cycm9=`echo $ymdhm9 | cut -c9-10`

ymdhm10="`/gpfs/hps3/emc/meso/save/Benjamin.Blake/advtime ${ymd}${cyc} -10 -1`"
echo $ymdhm10
cycm10=`echo $ymdhm10 | cut -c9-10`

rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_makeguess_${cycm9}
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_makebc_${cycm9}
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_makebc_${cycm10}
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_prep_cloud_${cycm9}
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_prep_radar_${cycm9}
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_prep_smoke_${cycm9}
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_ref2tten_${cycm9}
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_anl_${cycm9}
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_post_${cycm9}*
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_postmgr_${cycm9}*
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_postmgr_subh_${cycm9}*
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_wrfbufr_${cycm9}*
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_sndp_${cycm9}
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_fcst_pre_${cycm9}
rm -rf /gpfs/hps3/ptmp/Benjamin.Blake/hrrr_${dom}_fcst_${cycm9}

exit
