#!/bin/ksh
set -xa
export MP_IOAGENT_CNT=all
#
# Specify whether the run is production or development
#
export RUN_ENVIR=${RUN_ENVIR:-nco}

#####################################################################################
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to ${DATAROOT}
# DEV_ECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to ${COMROOT}/$NET/${envir}
# COM_OUT: Directory for output file, default to ${COMROOT}/$NET/${envir}
# gespath: Directory for the guess or restart files, default to ${GESROOT}/${envir}
#####################################################################################
if [ "$RUN_ENVIR" != nco ]      ### For Developers
then
  hrrr_ver=${hrrr_ver:-v2.0.0}
  PARA_CONFIG=${hrrr_para_config:-/meso/save/${LOGNAME}/hrrr.${hrrr_ver}/user/hrrr_para_config}
  if [ -s $PARA_CONFIG ] ; then . $PARA_CONFIG ; fi
  export userid=$LOGNAME
  export DATA_IN=${DATA_IN:-/gpfs/hps/ptmp/$userid}
fi

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hrrr}
export RUN=${RUN:-hrrr}
export model=${model:-hrrr}

export PS4='$SECONDS + '
date

########################################################
# obtain unique process id (pid) and make temp directory
########################################################
export DATA_IN=${DATA_IN:-${DATAROOT}}
export DATA=$DATA_IN/${jobid}
mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z
export tmmark=tm00

export pgmout="OUTPUT.$$"

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# GET_IOPROFILE - Run I/O statistics
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}

####################################
# Specify Execution Areas
####################################
export HOMEhrrr=${HOMEhrrr:-${NWROOT}/${NET}.${hrrr_ver}}
export SCRIPTShrrr=${SCRIPTShrrr:-$HOMEhrrr/scripts}
export FIXhrrr=${FIXhrrr:-$HOMEhrrr/fix}
export PARMhrrr=${PARMhrrr:-$HOMEhrrr/parm}
export EXEChrrr=${EXEChrrr:-$HOMEhrrr/exec}
export USHhrrr=${USHhrrr:-$HOMEhrrr/ush}

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. PDY

########################################
# Define Input Data Directories
########################################
# Hourly Radar Data
export COM_RAD=${COM_RAD:-${COMROOTp1}/hourly/prod}

# Define cycm1 since we need land-sfc fields for previous hour
export cycle=t${cyc}z
export cycm1=`expr $cyc - 1`
if [ "$cyc" = 00 ]; then
cycm1=23
else
cycm1=$(printf "%02d" $cycm1)
fi

##############################################
# Define COM directories
##############################################
export COM_IN=${COM_IN:-${COMROOT}/${NET}/${envir}}
export COM_OUT=${COM_OUT:-${COMROOT}/${NET}/${envir}}

export COMIN=$COM_IN/hrrr.${PDY}
export COMOUT=$COM_OUT/hrrr.${PDY}

mkdir -m 775 -p $COMOUT 

##############################################
# Define GES directories
##############################################
export gespath=${gespath:-${GESROOT}/${envir}}
export HRRRBC=$gespath/${RUN}/hrrrbc

mkdir -m 775 -p $HRRRBC
env

export DATA_RADAR=${DATA_RADAR:-${DATA_IN}/hrrr_prep_radar_${envir}_${cyc}}

########################################################
# Execute the script.
${HRRR_PREPREF2TTENSSH:-$HOMEhrrr/scripts/exhrrr_prep_ref2tten.sh.ecf}
########################################################
cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

export KEEPDATA=YES
##############################
# Remove the Temporary working directory
##############################
cd $DATA_IN
if [ ${KEEPDATA} = NO ] ; then rm -rf $DATA ; fi

date
