#!/bin/ksh -l
set -xa

########################################
# HRRR 3 km Analysis 
########################################

######################################################
# The following two variables could be defined in the
# loadleveler submission script (the ecf script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}
export SENDECF=${SENDECF:-YES}

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hrrr}
export RUN=${RUN:-hrrr}
export model=${model:-hrrr}

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to ${DATAROOT}
# SENDECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to ${COMROOT}/$NET/${envir}
# COM_OUT: Directory for output file, default to ${COMROOT}/$NET/${envir}
# gespath: Directory for the guess or restart files, default to ${GESROOT}/${envir}
#####################################################################################
if [ "$RUN_ENVIR" != nco ]      ### For Developers, "group_name" is passed from the ECF script
then
  group_name=${group_name:-meso}
  package_name=${package_name:-hrrr}
  . /${group_name}/save/${LOGNAME}/${package_name}${NWROOTprod}/parm/${package_name}_para_config
  export userid=${userid:-$LOGNAME}
  export DATA_IN=${DATA_IN:-/ptmpd1/$userid}
fi

export PS4='$SECONDS + '
date

####################################
# obtain unique process id (pid) and make temp directory
####################################
export DATA_IN=${DATA_IN:-${DATAROOT}}
export DATA=$DATA_IN/${jobid}
mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z
export tmmark=tm00

export pgmout="OUTPUT.$$"

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy files to /com directory
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}

####################################
# Specify Execution Areas
####################################
export HOMEhrrr=${HOMEhrrr:-${NWROOT}/${NET}.${hrrr_ver}}
export EXEChrrr=${EXEChrrr:-${HOMEhrrr}/exec}
export FIXhrrr=${FIXhrrr:-${HOMEhrrr}/fix}
export PARMhrrr=${PARMhrrr:-${HOMEhrrr}/parm}
export USHhrrr=${USHhrrr:-${HOMEhrrr}/ush}

export FIXcrtm=${FIXcrtm:-${NWROOTp1}/fix}

###########################################
# Run setpdy and initialize PDY variables
###########################################
setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COM_IN=${COM_IN:-${COMROOT}/${NET}/${envir}}
export COM_OUT=${COM_OUT:-${COMROOT}/${NET}/${envir}}
export COM=${COM:-COM_IN}
export COMIN=${COMIN:-${COM_IN}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COM_OUT}/${RUN}.${PDY}}
export COMINsst=${COMINsst:-${COMROOTp1}/gfs/prod}
export COMINsstp1=${COMINsstp1:-$COMROOTp1/gfs/prod}
export COMINsstp2=${COMINsstp2:-$COMROOT/gfs/prod}
export PREPDIR=${PREPDIR:-${COMROOT}/rap/${envir}/rap.${PDY}}
export COMRAP=${COMRAP:-${COMROOT}/rap/${envir}}
export COMRAP_E=${COMRAP_E:-${COMROOT}/rap/${envir}}
export PREPDIR2=${PREPDIR2:-${COMIN}}
export AIRCRAFT_REJECT=${AIRCRAFT_REJECT:-${HOMEhrrr}/parm}

export gespath=${gespath:-$GESROOT/${envir}}
export HRRRGES_ENKF=${HRRRGES_ENKF:-$gespath/${NET}/hrrrges_enkf}
env

########################################################
# Execute the script.
${HRRR_ANALSH:-$HOMEhrrr/scripts/exhrrr_analysis.sh.ecf}
########################################################

cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATA_IN
if [ ${KEEPDATA} = NO ] ; then rm -rf $DATA ; fi

date

