#!/bin/ksh -l
set -xa
export MP_IOAGENT_CNT=all
export MP_IO_BUFFER_SIZE=8M

########################################
# HRRR Post Processing
########################################

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the ecf script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}
export SENDECF=${SENDECF:-YES}

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hrrr}
export RUN=${RUN:-hrrr}
export model=${model:-hrrr}

###################################
# Load the GRIB Utilities module
####################################
. /usrx/local/Modules/default/init/ksh
module load grib_util

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to ${DATAROOT}
# SENDECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to ${COMROOT}/$NET/${envir}
# COM_OUT: Directory for output file, default to ${COMROOT}/$NET/${envir}
# gespath: Directory for the guess or restart files, default to ${GESROOT}/${envir}
#####################################################################################
if [ "$RUN_ENVIR" != nco ]      ### For Developers, "group_name" is passed from the ECF script
then
  group_name=${group_name:-meso}
  package_name=${package_name:-hrrr}
#  . /${group_name}/save/${LOGNAME}/${package_name}${NWROOTprod}/parm/${package_name}_para_config
  export userid=${userid:-$LOGNAME}
  export DATA_IN=${DATA_IN:-/ptmp/$userid}
fi

export PS4='$SECONDS + '
date

####################################
# obtain unique process id (pid) and make temp directory
####################################
export DATA_IN=${DATA_IN:-${DATAROOT}}
export DATA=$DATA_IN/${jobid}
mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z

export pgmout="OUTPUT.$$"

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy files to /com directory
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export ALERT_EXT=${ALERT_EXT:-}

####################################
# Specify Execution Areas
####################################
export HOMEhrrr=${HOMEhrrr:-${NWROOT}/${NET}.${hrrr_ver}}
export EXEChrrr=${EXEChrrr:-${HOMEhrrr}/exec}
export FIXhrrr=${FIXhrrr:-${HOMEhrrr}/fix}
export PARMhrrr=${PARMhrrr:-${HOMEhrrr}/parm}
export USHhrrr=${USHhrrr:-${HOMEhrrr}/ush}
export PARMutil=${PARMutil:-${HOMEhrrr}/util/parm}

export WGRIB2=${HOMEhrrr}/exec/hrrr_wgrib2
export CRTM=${CRTM:-$NWROOTp1/fix/crtm_2.0.5}

###########################################
# Run setpdy and initialize PDY variables
###########################################
setpdy.sh
. PDY
##############################################
# Define COM directories
##############################################
export COM_IN=${COM_IN:-${COMROOT}/${NET}/${envir}}
export COM_OUT=${COM_OUT:-${COMROOT}/${NET}/${envir}}

export COM=${COM:-${COM_IN}}
export COMIN=${COMIN:-${COM_IN}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COM_OUT}/${RUN}.${PDY}}
export PCOM=${PCOM:-${PCOMROOT}/${NET}}
export gespath=${gespath:-$GESROOT/${envir}}
export export HRRRGES_SFC=${HRRRGES_SFC:-$gespath/${RUN}/hrrrges_sfc}
mkdir -m 775 -p $COMOUT $PCOM

env

########################################################
# Execute the script.
export FCSTDIR=$DATA_IN/hrrr_fcst_${envir}_${cyc}
#export FCSTDIR=/tmpnwprd2/hrrr_fcst_${envir}_${cyc} #XXW
${HRRR_POSTSH:-$HOMEhrrr/scripts/exhrrr_post.sh.ecf}
########################################################

cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATA_IN
if [ ${KEEPDATA} = NO ] ; then rm -rf $DATA ; fi

date
