# makefile for nssl_porcess
#! /bin/sh -v

# Define the fortran compiler and options

include ./configure.process_jet

INCLD=  -I${NETCDF}/include -I../../../include
LIBS =  -L${WRFDIR}/external/io_netcdf -lwrfio_nf -L${NETCDF}/lib -lnetcdf \
        -L${GSILIBS}

OBJS = process_SST.o sst14k.o sstGlobal2RR.o netCDFsub_geo.o update_SST_netcdf_mass.o

all: process_SST

process_SST: ${OBJS}
	${FC} -o process_SST.exe ${FLAGS} ${OBJS} ${LIBS} 

.SUFFIXES : .F90 .f90 .o

.F90.o :
	${FC} ${FLAGS} ${INCLD} -c $<

.f90.o :
	${FC} ${FLAGS} ${INCLD} -c $<

clean:
	/bin/rm -f *.o *.exe
