#!/bin/sh 
#

mkdir /gpfs/hps3/stmp/Benjamin.Blake
mkdir /gpfs/hps3/stmp/Benjamin.Blake/work
rm /gpfs/hps3/stmp/Benjamin.Blake/work/*
cd /gpfs/hps3/stmp/Benjamin.Blake/work

cp /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod_final/hrrr.v4.0.0/ecf/post/wrfbufr/jhrrr_wrfbufr_fXX.ecf .
hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48"
for fhr in $hours; do
 cp jhrrr_wrfbufr_fXX.ecf jhrrr_wrfbufr_f${fhr}.ecf
 vi jhrrr_wrfbufr_f${fhr}.ecf << EOF 
   :1,\$ s/XX/${fhr}
   :wq
EOF
mv jhrrr_wrfbufr_f${fhr}.ecf /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod_final/hrrr.v4.0.0/ecf/post/wrfbufr/.
done
exit
