#!/bin/sh 
#

mkdir /lfs/h2/emc/ptmp/Benjamin.Blake
mkdir /lfs/h2/emc/ptmp/Benjamin.Blake/work
cd /lfs/h2/emc/ptmp/Benjamin.Blake/work

. /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/versions/hrrr.ver
cp /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/prep/jhrrr_prep_radar_XXXX.qsub .
cp /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/prep/jhrrr_prep_radar_XX60.qsub .
#cycles="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
cycles="00 03 06 09 12 15 18 21"
minutes="16 30 46"
for cyc in $cycles; do
for fmin in $minutes;do
 cp jhrrr_prep_radar_XXXX.qsub jhrrr_prep_radar_${cyc}${fmin}.qsub 
 vi jhrrr_prep_radar_${cyc}${fmin}.qsub << EOF 
   :1,\$ s/HH/${cyc}
   :wq
EOF
 vi jhrrr_prep_radar_${cyc}${fmin}.qsub << EOF
   :1,\$ s/MM/${fmin}
   :wq
EOF
mv jhrrr_prep_radar_${cyc}${fmin}.qsub /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/prep/.
done

cp jhrrr_prep_radar_XX60.qsub jhrrr_prep_radar_${cyc}60.qsub
vi jhrrr_prep_radar_${cyc}60.qsub << EOF
  :1,\$ s/HH/${cyc}
  :wq
EOF
vi jhrrr_prep_radar_${cyc}60.qsub << EOF
  :1,\$ s/MM/60
  :wq
EOF
mv jhrrr_prep_radar_${cyc}60.qsub /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/prep/.
done
exit
