#!/bin/sh 
#

mkdir /gpfs/hps3/stmp/Benjamin.Blake/work
cd /gpfs/hps3/stmp/Benjamin.Blake/work
. /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.v4.0.0/hrrr.ver

cp /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/sms/post/post/jhrrr_post_fXX_HH.bsub .
#hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36"
hours="37 38 39 40 41 42 43 44 45 46 47 48"
cycles="00 06 12 18"
#hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18"
#cycles="01 02 03 04 05 07 08 09 10 11 13 14 15 16 17 19 20 21 22 23"
for cyc in $cycles;do
echo $cyc $cyc
for fhr in $hours; do
 echo $fhr
 cp jhrrr_post_fXX_HH.bsub jhrrr_post_f${fhr}_${cyc}.bsub
 vi jhrrr_post_f${fhr}_${cyc}.bsub << EOF 
   :1,\$ s/XX/${fhr}
   :1,\$ s/HH/${cyc}
   :wq
EOF
mv jhrrr_post_f${fhr}_${cyc}.bsub /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/sms/post/post/.
done
done
exit
