#!/bin/sh 
#

mkdir /lfs/h2/emc/ptmp/Benjamin.Blake/work
cd /lfs/h2/emc/ptmp/Benjamin.Blake/work
. /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/versions/hrrr.ver

cp /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/post/post/jhrrr_post_fXX_HH.qsub .
#cycles="00 06 12 18"
#hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48"
#for cyc in $cycles;do
#echo $cyc $cyc
#for fhr in $hours; do
# echo $fhr
# cp jhrrr_post_fXX_HH.qsub jhrrr_post_f${fhr}_${cyc}.qsub
# vi jhrrr_post_f${fhr}_${cyc}.qsub << EOF 
#   :1,\$ s/XX/${fhr}
#   :1,\$ s/HH/${cyc}
#   :wq
#EOF
#mv jhrrr_post_f${fhr}_${cyc}.qsub /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/post/post/.
#done
#done

hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18"
cycles="03 09 15 21"
for cyc in $cycles;do
echo $cyc $cyc
for fhr in $hours; do
 echo $fhr
 cp jhrrr_post_fXX_HH.qsub jhrrr_post_f${fhr}_${cyc}.qsub
 vi jhrrr_post_f${fhr}_${cyc}.qsub << EOF 
   :1,\$ s/XX/${fhr}
   :1,\$ s/HH/${cyc}
   :wq
EOF
mv jhrrr_post_f${fhr}_${cyc}.qsub /lfs/h2/emc/lam/noscrub/Benjamin.Blake/nwprod/hrrr.${hrrr_ver}/smsak/post/post/.
done
done

exit
