#!/bin/sh 
#

mkdir /gpfs/hps3/stmp/Benjamin.Blake
mkdir /gpfs/hps3/stmp/Benjamin.Blake/work
cd /gpfs/hps3/stmp/Benjamin.Blake/work
cp /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.v3.0.0/sms/post/jhrrr_postmgr_subh_XX.bsub .
cycles="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
for cyc in $cycles; do
 cp jhrrr_postmgr_subh_XX.bsub jhrrr_postmgr_subh_${cyc}.bsub
 vi jhrrr_postmgr_subh_${cyc}.bsub << EOF 
   :1,\$ s/XX/${cyc}
   :wq
EOF
mv jhrrr_postmgr_subh_${cyc}.bsub /gpfs/hps3/emc/meso/save/Benjamin.Blake/nwprod/hrrr.v3.0.0/sms/post/.
done
exit
